from _typeshed import Incomplete

class MariaDbInterface:
    user: Incomplete
    password: Incomplete
    host: Incomplete
    port: Incomplete
    database: Incomplete
    def __init__(self, user: str, password: str, host: str, port: int, database: str, *arg, **kwargs) -> None: ...
    def connect(self) -> None: ...
    def fetchallAsDict(self, query: tuple) -> list[dict[str, any]]: ...
    def close(self) -> None: ...
