class SqliteInterface:
    def __init__(self, db_file, *args, **kwargs) -> None: ...
    def connect(self) -> None: ...
    def fetchallAsDict(self, query: tuple) -> list[dict[str, any]]: ...
    def close(self) -> None: ...
