from ..Builtins.dataObjects import UserSettings as UserSettings, commandObj as commandObj, quoteObj as quoteObj, streamTimerObj as streamTimerObj
from .DatabaseInterface import Database as Database
from .SqlStatments import COMMANDS_SQL as COMMANDS_SQL, SETTINGS_SQL as SETTINGS_SQL
from _typeshed import Incomplete
from pickle import dumps as dumps, loads as loads

class UserDatabase:
    database: Database
    id: int
    def __init__(self, id: int) -> None: ...
    def loadSettings(self) -> UserSettings: ...
    def loadCommands(self) -> dict[str, commandObj]: ...
    def updateCommand(self, command: commandObj): ...
    def addCommand(self, command, data, cooldown, roleRequired, usage, enabled) -> None: ...
    def loadQuotes(self) -> dict[str, quoteObj]: ...
    def loadStreamTimer(self) -> streamTimerObj: ...
    def updateCommandLastUsed(self, cmd) -> None: ...
