from .commandBase import commandBase as commandBase
from .commandParser import CommandParser as CommandParser
from .dataObjects import commandObj as commandObj
from Twitch_Edog0049a.ChatInterface import Chat as TCI
from Twitch_Edog0049a.ChatInterface.MessageHandler import Message as Message
from random import choice as choice
from time import time as time

class command(commandBase):
    def __init__(self, tci: TCI, message: Message, user) -> None: ...
    def print(self) -> None: ...
    def add(self) -> None: ...
    def createCommandObject(self, cmdParts) -> commandObj: ...
    def remove(self) -> None: ...
    def run(self, cmd: str): ...
    def onCoolDown(self, commandObj) -> bool: ...
    @property
    def commands(self) -> set: ...
    def isCommand(self, command: str) -> bool: ...
